# Generated by Django 2.1.7 on 2019-03-08 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190308_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 8, 19, 58, 57, 755080), verbose_name='dato'),
        ),
    ]
