# Generated by Django 2.1.7 on 2019-03-09 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190308_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 9, 11, 45, 17, 219718), verbose_name='dato'),
        ),
    ]
