# Generated by Django 2.1.7 on 2019-03-12 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190312_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 12, 13, 11, 42, 374638), verbose_name='dato'),
        ),
    ]
