# Generated by Django 2.1.7 on 2019-03-12 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190312_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 12, 13, 19, 40, 260013), verbose_name='dato'),
        ),
    ]
