# Generated by Django 2.1.7 on 2019-03-12 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190312_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addplate',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 12, 14, 47, 49, 839097), verbose_name='dato tilføjet'),
        ),
    ]
