# Generated by Django 2.1.7 on 2019-03-12 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190312_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addplate',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 12, 15, 47, 39, 928281), verbose_name='dato tilføjet'),
        ),
        migrations.AlterField(
            model_name='addplate',
            name='plateNumber',
            field=models.CharField(max_length=10, null=True, verbose_name='Nummerplade'),
        ),
    ]
