# Generated by Django 2.1.7 on 2019-03-19 12:00

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190312_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addplate',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 13, 0, 7, 311491), verbose_name='dato tilføjet'),
        ),
        migrations.AlterField(
            model_name='addplate',
            name='plateNumber',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Må ikke indeholde mellemrum.', regex='/\\S+/'), django.core.validators.RegexValidator(code='nomatch', message='Må ikke indeholde mellemrum.', regex='[N][o][n][e]')], verbose_name='Nummerplade'),
        ),
    ]
