# Generated by Django 2.1.7 on 2019-03-19 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190319_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addplate',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 13, 7, 58, 193417), verbose_name='dato tilføjet'),
        ),
    ]
