# Generated by Django 2.1.7 on 2019-03-19 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190319_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addplate',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 13, 11, 29, 760743), verbose_name='dato tilføjet'),
        ),
    ]
