# Generated by Django 2.1.7 on 2019-03-19 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190319_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberplate', models.CharField(max_length=8)),
                ('entered', models.DateTimeField(default=datetime.datetime(2019, 3, 19, 14, 20, 15, 508833))),
                ('exited', models.DateTimeField(default=datetime.datetime(2019, 3, 19, 14, 20, 15, 508833))),
                ('userid', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='plates',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 14, 20, 15, 508833), verbose_name='dato tilføjet'),
        ),
        migrations.AlterField(
            model_name='plates',
            name='plateNumber',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Nummerplade'),
        ),
    ]
