# Generated by Django 2.1.7 on 2019-03-19 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20190319_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='entered',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 14, 44, 34, 340522)),
        ),
        migrations.AlterField(
            model_name='log',
            name='exited',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 14, 44, 34, 340522)),
        ),
        migrations.AlterField(
            model_name='plates',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 14, 44, 34, 340522), verbose_name='dato tilføjet'),
        ),
    ]
