# Generated by Django 2.1.7 on 2019-03-19 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20190319_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingentity',
            name='available',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='parkingentity',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='log',
            name='entered',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 15, 33, 39, 586581)),
        ),
        migrations.AlterField(
            model_name='log',
            name='exited',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 15, 33, 39, 586581)),
        ),
        migrations.AlterField(
            model_name='plates',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 15, 33, 39, 586581), verbose_name='dato tilføjet'),
        ),
    ]
